### ISSUE TITLE
你好。还能恢复一下https://gitee.com/ineo6/hosts/raw/master/hosts 这这个服务吗

### ISSUE THREAD

**Issue by kongbg** [ineo6/fast-dev#1]
之前用你的这个地址https://gitee.com/ineo6/hosts/raw/master/hosts 获取host，现在已经不能用了，有替代的吗

**Comment by apgk** [comment]
> 

https://ineo6.github.io/hosts/

**Comment by kongbg** [comment]
> 

拴q
