### ISSUE TITLE
M2 mac pro 安装后打开报 文件已损坏

### ISSUE THREAD

**Issue by NewPZP** [ineo6/fast-dev#2]

**Comment by NewPZP** [comment]
https://gitee.com/link?target=https%3A%2F%2Fghproxy.com%2Fhttps%3A%2F%2Fgithub.com%2Fineo6%2Ffast-dev%2Freleases%2Fdownload%2Fv1.0.1%2FFastDev_mac_arm64_1.0.1.dmg  用的是这个

**Comment by ineo6** [comment]
看下 https://zhuanlan.zhihu.com/p/114919138
